services:

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: twotierdb
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pYOUR_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: flask-web
    ports:
      - "5000:5000"
    depends_on:
      - mysql
  