apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config

data:
  DB_HOST: "mysql-service"
  DB_NAME: "twotierdb"
  DB_USER: "root"
  MYSQL_DATABASE: "twotierdb"

  init.sql: |
    USE twotierdb;

    CREATE TABLE IF NOT EXISTS messages (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        message TEXT NOT NULL
    );
