apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql

            # making the table messages automatically in the database when the pod is recreated or restarted
            - name: mysql-init
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
              readOnly: true

          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: MYSQL_DATABASE
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc

        # making the table messages automatically in the database when the pod is recreated or restarted
        - name: mysql-init
          configMap:
            name: flask-config
            items:
              - key: init.sql
                path: init.sql
